---
- name: Initial setup
  hosts: athos
  become: true

  roles:
    - role: kube-dependencies

- name: Configure master node
  hosts: athos
  become: true
  gather_facts: false

  roles:
    - role: kube-master
