---
- name: Initial setup
  hosts: nodes
  gather_facts: false
  tags: ['kube-dependencies']

  roles:
    - role: kube-dependencies

- name: Configure the master node
  hosts: master
  gather_facts: false
  tags: ['kube-master']

  roles:
    - role: kube-master

- name: Configure the worker nodes
  hosts: workers
  gather_facts: false
  tags: ['kube-worker']

  roles:
    - role: kube-worker
